apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: future-k8s-deployment
spec:
  selector:
    matchLabels:
      app: future
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: future
    spec:
      containers:
        - name: future
          image: ash9659/future # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
---
apiVersion: apps/v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: future-k8s-service
spec:
  selector:
    app: future
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.











